services:
- docker
script: docker-compose run test
notifications:
  slack:
    secure: XX4h22l27fJgMJvc6aE8QzL76BqP7wOMXjfNfUZsnugIkNvzcSj6u4ScrMLXB0NXExOIkgtw0ZvSq/uKLNaJuW+kJdZU1XNvjEk4bqpJcOSan38Fl58z98W+N7tjkOqvwRKQRGafixWjzIE6SGR7EtTXyqM12fY8krYSHpofyFIHlcDBIDE2X8o1eWA05Ihnl+PefTdNXC7nJ14ECIoKQ3Zj8w824vjTjVrrHCQHl2Djybo9wXfgNCcDay8aMkXdGe7iyGdIa0XhD7vaK/CB9NtoF2KjCd6hIHREnbVL8iEUNsTtleOU22D9EGlkCH4714M1xQayizmEK3Ov7Z3RXXuOzG+gTVk8P7HZeidC0Tzutrym9BjAvPCFxXHG7ammRcSkOST5Bas96l6MEdPqWB4bI0dLFINIyoeIj/jO7R5UU0WEp2qBP6KJcVz39jHSTYQR34n1eD9wWLcOTcgD5clCbxiS0Ba3hqpC2Iz2uXca4IlFb8G0HOM29Ntu5BuM4pi5zY8BU818lMRbR8GAMJmRHoeteX9yFjJQnMWp4HpsTzGjfgpRWAmJTn85HA5Wzm+pKeeIN1oJK8UGQp9uphOAQRb1zuwO2JmTM6Ac1SPlePegxK/cLSNumzioVUIz2Mo3FCDj5+ULu8MOY9AhOjJXjahJXyDX3midZ4ItPFQ=
