services:
- docker
script: docker-compose run test
notifications:
  slack:
    on_pull_requests: false
    secure: MFbeaRP3DIUiUtPxmPR/jAofx5XdLxs1OnNBiu48u+i/G0jsLD69p9UCuQoo1Z8y83hS8+rXK/khi00IDK3yZlpfpv8RwaQ5O3bcIw7yie0K6LT7Dy0eGMHqXwM/bivPMfqzhlHOaN190iWRCZvCmGnRiJW8jpSowxjTK15VlBfiyfEpsOfNclpZ1D55AJ7xROQNGG3q2gyxlw4ZwW2VTssfwAvw86iON8+7EO4YcoufaYo7Mn9MgxrYtowW0PXNbwMU1BlTuGn3fKgA3getqrJiFPt8laeuhpjzOYJ2xNQSMKJzlqUWwc41ey0jt9m1fx/I1zsrMEvx5Kc3WRs29LSWjhLwDodJ1MuVxZp8BmoTW6IWPJFTv1cLKcp0GiFyS9RGO529khVDThYAyAvnJJt5uQnC4Nij3/4UdmOCafGlx1S6sas4mJAMhG4O5nGTO6TQuTeNMarSvi2DKjNmcr/t6vSmklaUH3dfy6fgq2Vb/XH/FnVGl8vhiIYWKU+KzJe2txpn4bNoLAdicZZPbO1N0c1HWvljsjjkuGRwtnC8Qwdal3ni/FkQ+G/n/VUsUkYr10RSOUqg9v3wh1ItxseXsxQUdxF+vd8XF8V5818niJN0mQ42cJKtSOawnochakn8HKnUayQ9bRVa9TDZr5f19yna6IG8Cs4QLgCffGk=
