version: '3'
services:
  windbreaker-hooks:
    build: .
    command: 'npm start'
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - .:/usr/windbreaker-hooks
      - /usr/windbreaker-hooks/node_modules
      # uncomment to link and/or replace first path if service utils are located elsewhere
      # - ../windbreaker-service-util:/usr/windbreaker-hooks/node_modules/windbreaker-service-util
    environment:
      SERVICE_ENVIRONMENT: 'docker'
    ports:
      - 8080:8080
  test:
    build: .
    command: 'npm run test:docker:ci'
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - .:/usr/windbreaker-hooks
      - /usr/windbreaker-hooks/node_modules
      # uncomment to link and/or replace first path if service utils are located elsewhere
      # - ../windbreaker-service-util:/usr/windbreaker-hooks/node_modules/windbreaker-service-util
    environment:
      SERVICE_ENVIRONMENT: 'docker'
  postgres:
    image: 'postgres:9.6.3-alpine'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'windbreaker-hooks'
    ports:
      - 5432
  rabbitmq:
    image: 'rabbitmq:3.6.10-alpine'
    ports:
      - 5672
