FROM node:8.1.2-alpine

ENV HOME=/usr/windbreaker-hooks

RUN mkdir -p $HOME

WORKDIR $HOME

RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh

ADD . $HOME

RUN ls
RUN npm install

CMD [ "npm", "start" ]
