httpServerPort: 3000
amqUrl: 'amqp://127.0.0.1:5672'
redisClusterNodes:
  - host: '127.0.0.1'
    port: 7000
  - host: '127.0.0.1'
    port: 7000
knex:
  client: 'pg'
  connection:
    host: '127.0.0.1'
    user: 'postgres'
    password: 'postgres'
    database: 'windbreaker'
  debug: true
