amqUrl: 'amqp://rabbitmq'
redisClusterNodes:
  - host: '127.0.0.1'
    port: 7000
  - host: '127.0.0.1'
    port: 7000
knex:
  client: 'pg'
  connection:
    host: 'postgres'
    user: 'postgres'
    password: 'postgres'
    database: 'windbreaker_hooks'
  debug: true
  migrations:
    tableName: 'migrations'

# Path to github hook secret key, relative to project root (not home)
# Absolute paths work as well
githubWebhookSecretPath: '~/.secrets/github-hooks-secret'
