amqUrl: 'amqp://rabbitmq'
redisClusterNodes:
  - host: '127.0.0.1'
    port: 7000
  - host: '127.0.0.1'
    port: 7000
knex:
  client: 'pg'
  connection:
    host: 'postgres'
    user: 'postgres'
    password: 'postgres'
    database: 'windbreaker'
  debug: true
githubWebhookSecret: 'someSuperSecretSharedKey'
